### PR TITLE
Add benchmarks to sublist with Criterion

### PR DESCRIPTION
**Pull request by senekor**
I've had a little fun trying to setup Criterion. There is a readme with a few pointers about how I got started.

I was very surprised by the results. rayon seems to be incredibly fast for large inputs where the sub slice can be found. It almost makes me think I did something wrong, it looks too good to be true...

If you want to, you can add your own threads based solution to the benchmarks :-)

### CODE REVIEW

**Comment by senekor** [comment]
(I'll leave it up to you if you actually want to merge any of this. You can do with it what you like. I just opened this PR for discussion.)

**Comment by EvgeniiaVak** [comment]
Wow, nice, thank you so much! I will definitely look into this... The pr is a draft, so I shouldn't merge it yet, right?

**Comment by senekor** [comment]
> The pr is a draft, so I shouldn't merge it yet, right?

You can totally merge this if you're happy with it. The benchmarks run and serve their purpose, it's not an unfinished work in progress. Or you can (re)use any part of this however you want.

**Comment by senekor** [comment]
Maybe the large file annoys you? It would probably be possible to generate some vector of data during setup of the benchmarks, so there's not a huge file in the repo. So yeah, depends on how you like your setup and your repo organized.

**Review by EvgeniiaVak — APPROVED** [review]

**Comment by EvgeniiaVak** [comment]
Perfect, Thanks a lot!

**Pull request merged**
